public delegate void BasicAction();
public delegate void BasicAction<in T>(T value);
public delegate void BasicAction<in T1, in T2>(T1 value1, T2 value2);
public delegate void BasicAction<in T1, in T2, in T3>(T1 value1, T2 value2, T3 value3);
public delegate void BasicAction<in T1, in T2, in T3, in T4>(T1 value1, T2 value2, T3 value3, T4 value4);
public delegate R BasicReturnAction<out R>();
public delegate R BasicReturnAction<in T1, out R>(T1 value1);
public delegate R BasicReturnAction<in T1, in T2, out R>(T1 value1, T2 value2);
public delegate R BasicReturnAction<in T1, in T2, in T3, out R>(T1 value1, T2 value2, T3 value3);
public delegate R BasicReturnAction<in T1, in T2, in T3, in T4, out R>(T1 value1, T2 value2, T3 value3, T4 value4);